In [1]:
import numpy as np
import pandas as pd
import geopandas as gpd
import folium
import datetime
import pickle

In [ ]:
# Import the file as a Pandas DataFrame
fp = '../data/july.csv'
july = pd.read_csv(fp)
july.head(10)

In [72]:
company_dict = {'Bird':0, 'Lyft': 1, 'Gotcha': 2, 'Lime': 3, 'Spin': 4, 'Jump': 5, 'Bolt': 6}
july.companyname = july.companyname.replace(company_dict)
july.head(10)

,pubdatetime,latitude,longitude,sumdid,sumdtype,chargelevel,sumdgroup,costpermin,companyname
0,2019-07-01 00:00:33.550000,36.156678,-86.809004,Powered635135,Powered,22.0,scooter,0.15,1
1,2019-07-01 00:00:34.973000,36.145674,-86.794138,Powered790946,Powered,33.0,scooter,0.15,1
2,2019-07-01 00:00:41.183000,36.179319,-86.751538,Powered570380,Powered,76.0,scooter,0.15,1
3,2019-07-01 00:00:41.620000,36.152111,-86.803821,Powered240631,Powered,43.0,scooter,0.15,1
4,2019-07-01 00:00:45.087000,36.149355,-86.797550,Powered970404,Powered,52.0,scooter,0.15,1
5,2019-07-01 00:00:46.847000,36.168153,-86.777374,Powered912425,Powered,80.0,scooter,0.15,1
6,2019-07-01 00:00:50.500000,36.143266,-86.809886,Powered667919,Powered,60.0,scooter,0.15,1
7,2019-07-01 00:00:50.520000,36.177355,-86.750667,Powered523737,Powered,85.0,scooter,0.15,1
8,2019-07-01 00:00:53.273000,36.158546,-86.774062,Powered689152,Powered,72.0,scooter,0.15,1
9,2019-07-01 00:00:56.293000,36.177708,-86.750043,Powered211807,Powered,99.0,scooter,0.15,1

In [74]:
july.pubdatetime = pd.to_datetime(july['pubdatetime'])

In [75]:
july.to_pickle("../data/july.pkl")

In [76]:
july_scooters = july[['pubdatetime', 'latitude', 'longitude', 'sumdid', 'chargelevel', 'companyname']]

In [77]:
july_scooters.iloc[6]

pubdatetime    2019-07-01 00:00:50.500000
latitude                        36.143266
longitude                      -86.809886
sumdid                      Powered667919
chargelevel                          60.0
companyname                             1
Name: 6, dtype: object

In [80]:
july_scooters = july_scooters.set_index('pubdatetime')

In [85]:
july_scooters.head()

,latitude,longitude,sumdid,chargelevel,companyname
pubdatetime,,,,,
2019-07-01 00:00:33.550,36.156678,-86.809004,Powered635135,22.0,1
2019-07-01 00:00:34.973,36.145674,-86.794138,Powered790946,33.0,1
2019-07-01 00:00:41.183,36.179319,-86.751538,Powered570380,76.0,1
2019-07-01 00:00:41.620,36.152111,-86.803821,Powered240631,43.0,1
2019-07-01 00:00:45.087,36.149355,-86.797550,Powered970404,52.0,1

In [84]:
##july 1 was a monday
july_1_scooters = july_scooters[july_scooters['pubdatetime']<='2019-07-02 00:00:00.000']

KeyError: 'pubdatetime'

In [83]:
# Create an empty list
df_hour_list = []

# Create a series with the different hours of the day
hours = pd.Series(july_scooters.index.hour.unique().sort_values())

# Create a list of points for each hour of the day
def create_list(hour):
    df_hour_list.append(july_scooters.loc[july_scooters.index.hour == hour,
                                ['latitude',
                                 'longitude']].
                        groupby(['latitude', 
                                 'longitude']).sum().reset_index().values.tolist())
hours.apply(create_list);

KeyboardInterrupt: